const String Login_title = 'Login';
const String SignUp_title = 'Sign Up';
const String mainScreenTitle = 'Hello,';
const String mainScreenDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";
const String mainQuote1="Happiness";
const String mainQuote2="is not";
const String mainQuote3="in money ,";
const String mainQuote4="but in";
const String mainQuote5="Shopping ..";